# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Yuchen Zhuang
title: ECE Graduate Student
email: yczhuang@gatech.edu
website: night-chen.github.io

# Social links
twitter_username: facespics
github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Yuchen Zhuang. I am a graduate student majoring in Electrical and Computer Engineering (ECE) in Georgia Institute of Technology. My research interests are mainly in <mark>Natural Language Processing</mark> and <mark>Data mining</mark>, under the direction of Prof. Chao Zhang. I am studying in uncertainty quantifications in NLP tasks and fake news detection at present. Before entering graduate school, I accomplished my undergraduate study in Southeast University, majoring in information Engineering. I worked under the supervision of Prof. Chuan Zhang and mainly researched in DNA computing and multi-scale communication system.  I really enjoy doing interesting things! :D
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
TBD

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
