# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Yuchen Zhuang
title: ECE Graduate Student
email: yczhuang@gatech.edu
website: night-chen.github.io

# Social links
twitter_username: facespics
github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/photo_zyc.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Yuchen Zhuang. I am a graduate student majoring in Electrical and Computer Engineering (ECE) in [Georgia Institute of Technology](https://www.gatech.edu/). My research interests are mainly in <mark>Natural Language Processing</mark> and <mark>Data mining</mark>, under the direction of [Prof. Chao Zhang](http://chaozhang.org/). I am studying in uncertainty quantifications in NLP tasks and zero-shot event extraction from Twitter data at present. Before entering graduate school, I accomplished my undergraduate study in [Southeast University](https://www.seu.edu.cn/english), majoring in information Engineering. I worked under the supervision of [Prof. Chuan Zhang](https://www.researchgate.net/profile/Chuan_Zhang24) and mainly researched in mathematical and probabilistic modeling in multi-scale communication system. I really enjoy doing interesting things! :D

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

more_title: Publications #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraph


  #### Natural Language Processing and Machine Learning (Graduation Time):   
    **Compositional Graphical Modular Network for Event Extraction on COVID-19 Related Tweets**
    **Yuchen Zhuang**, Chao Zhang   
    Targeting *Annual Conference of the North American Chapter of the Association for Computational Linguistics (NAACL-HLT)*, 2021    
    [**Calibrated Language Model Fine-tuning for In- and Out-of-Distribution Data**](https://arxiv.org/pdf/2010.11506.pdf)   
    Lingkai Kong, Haoming Jiang, **Yuchen Zhuang**, Jie Lyu, Tuo Zhao, Chao Zhang   
    *The 2020 Conference on Empirical Methods in Natural Language Processing (EMNLP)*, 2020   
    **EXAM-An Explainable Attention-based Model for COVID-19 Automatic Diagnosis**
    Wenqi Shi, Li Tong, **Yuchen Zhuang**, Yuanda Zhu, Dongmei May Wang   
    *ACM Conference on Bioinformatics, Computational Biology, and Health Informatics (ACM BCB)*, 2020   


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
